language: bash

env:
  global:
    - ENC_SSH_KEY=./id_rsa.enc
    - REPO_URL="git@github.com:sigo/polish-dictionary.git"
    - DOCKER_IMAGE=polish-dictionary
    - RESULT_DIR=dist/

sudo: required

git:
  depth: false

services:
  - docker

before_script:
  - docker build -t "${DOCKER_IMAGE}" .

script:
  - docker run -v "$(pwd)/${RESULT_DIR}:/code/${RESULT_DIR}" "${DOCKER_IMAGE}"
  # - docker run -e RESULT_DIR -v "$(pwd)/${RESULT_DIR}:/code/${RESULT_DIR}" "${DOCKER_IMAGE}"
  # - ./scripts/deploy.sh
