language: bash

env:
  - RESULT_DIR=dist/

sudo: required

services:
  - docker

before_script:
  - docker build -t polish-dictionary .

script:
  - docker run -v "$(pwd)/${RESULT_DIR}:/code/${RESULT_DIR}" polish-dictionary

after_success:
  - ls "${RESULT_DIR}"

after_script:
- ls "${RESULT_DIR}"
