language: generic

env:
  - RESULT_FILE = pl.txt

sudo: required

services:
  - docker

before_script:
  - docker build -t polish-dictionary .
  # - docker run -v dist:/code/dist/ polish-dictionary

script:
  - echo $RESULT_FILE
  - echo "${RESULT_FILE}"
  - ls -la
