language: bash

env:
  - ENC_SSH_KEY=./id_rsa.enc SSH_KEY=./id_rsa DOCKER_IMAGE=polish-dictionary RESULT_DIR=dist/

git:
  depth: false

sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_4abc9283474e_key -iv $encrypted_4abc9283474e_iv -in "${ENC_SSH_KEY}" -out "${SSH_KEY}" -d
  - chmod 600 "${SSH_KEY}"
  - eval `ssh-agent -s`
  - ssh-add "${SSH_KEY}"
  - rm "${SSH_KEY}"

before_script:
  - docker build -t "${DOCKER_IMAGE}" .

script:
  - docker run -e RESULT_DIR -v "$(pwd)/${RESULT_DIR}:/code/${RESULT_DIR}" "${DOCKER_IMAGE}"
  - git add "${RESULT_DIR}"
  - git commit -m "Update"
  - git push
