language: bash

env:
  # TODO: Think about simplification variables (are they all needed?)
  global:
    - DOCKER_IMAGE=polish-dictionary
    - RESULT_DIR=dist/
    - RESULT_DICTIONARY=pl.txt

sudo: required

git:
  depth: false

services:
  - docker

before_script:
  - docker build -t "${DOCKER_IMAGE}" .

script:
  - docker run -e RESULT_DIR -e RESULT_DICTIONARY -v "$(pwd)/${RESULT_DIR}:/code/${RESULT_DIR}" "${DOCKER_IMAGE}"
  - ./deploy.sh # TODO: Skip when travis is pushing to repo or it's pull request
