language: node_js
node_js:
  - "lts/*"

env:
  global:
    - DOCKER_IMAGE="polish-dictionary" # Name of docker image
    - DICTIONARY="dist/pl.txt" # Relative path to dictionary file

# Required to use docker
sudo: required

# Clone full repository history instead of last 50 commits
# TODO: Check is this required, I don't remember reason of this decision; skipping this will reduce cloning repo time
git:
  depth: false

# Needed for building and running docker images (using `docker` command in general)
services:
  - docker

before_script:
  - ./scripts/docker_build.sh

script:
  - ./scripts/docker_run.sh

# TODO: Skip infinite-recurring CI's jobs and when it's github pull request
after_success:
  - exit 0 # TODO: Remove after finished development
  # TODO: Run readme builder
  - ./scripts/dictionary_deploy.sh
