language: bash

env:
  - DOCKER_IMAGE=polish-dictionary RESULT_DIR=dist/

sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_4abc9283474e_key -iv $encrypted_4abc9283474e_iv -in id_rsa.enc -out id_rsa -d
  - ssh-add ./id_rsa

before_script:
  - docker build -t "${DOCKER_IMAGE}" .

script:
  - docker run -e RESULT_DIR -v "$(pwd)/${RESULT_DIR}:/code/${RESULT_DIR}" "${DOCKER_IMAGE}"

after_success:
  - git add "${RESULT_DIR}"
  - git commit -m "Update"
  - git log -n1
