language: generic

env:
  - RESULT_FILE = pl.txt
  - TEST_FILE=pl.txt

sudo: required

services:
  - docker

before_script:
  - docker build -t polish-dictionary .
  # - docker run -v dist:/code/dist/ polish-dictionary
  - eccho "${RESULT_FILE}"
  - eccho "${TEST_FILE}"
