language: bash

env:
  - RESULT_DIR=dist/

sudo: required

services:
  - docker

before_script:
  - docker build -t polish-dictionary .

script:
  - docker run -e RESULT_DIR -v "$(pwd)/${RESULT_DIR}:/code/${RESULT_DIR}" polish-dictionary

after_success:
  - git add "${RESULT_DIR}"
  - git commit -m "Update"
  - git log -n1
