language: bash

env:
  global:
    - DOCKER_IMAGE="polish-dictionary"
    - DICTIONARY="dist/pl.txt"

sudo: required

git:
  depth: false

services:
  - docker

before_script:
  - ./scripts/docker_build.sh

script:
  - ./scripts/docker_run.sh
  - ./scripts/deploy.sh # TODO: Skip when travis is pushing to repo or it's pull request
